name: "Build nx-tweaks"

on:
  push:
    branches:
      - "main"
  workflow_dispatch:

jobs:
  Build-Uberhand:
    name: "Release"
    runs-on: "ubuntu-latest"
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Downloading latest Uberhand
        run: |
          mkdir .release/
          wget -P .release/ "https://github.com/efosamark/Uberhand-Overlay/releases/latest/download/ovlmenu.ovl" 

      - name: Compressing Manual Version
        run:  |
          rm -f LICENSE
          rm -rf images
          rm -f README.md
          mkdir -p ".release/switch/.overlays"
          mkdir -p ".release/switch/.packages/System Tweaks"
          mv .release/ovlmenu.ovl .release/switch/.overlays/ovlmenu.ovl
          cp -r ./* ".release/switch/.packages/System Tweaks"
          zip -r ".release/nx-tweaks-2Manual.zip" ".release/switch"

      - name: Compressing Updater Version
        run:  |
          rm -rf .release/switch
          mkdir -p ".updater/"
          cp -r ./* ".updater/"
          zip -r "files.zip" ".updater/"
          mkdir -p ".updater/System Tweaks"
          mv files.zip .updater/System Tweaks/files.zip
          echo ";version='Open to init'" > .updater/System Tweaks/config.ini
          echo -e "[Init]\ncatch_errors\ndelete '/switch/.packages/files.zip'\nmove '/switch/.packages/System Tweaks/files.zip' '/switch/.packages/files.zip'\ndelete '/switch/.packages/System Tweaks/'\nunzip '/switch/.packages/files.zip' '/switch/.packages/System Tweaks/'\ndelete '/switch/.packages/files.zip'" > .updater/System Tweaks/init.ini
          zip -r ".release/nx-tweaks-1Updater.zip" ".updater/System Tweaks/"

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          draft: true
          generate_release_notes: true
          files: |
            .release/nx-tweaks-1Updater.zip
            .release/nx-tweaks-2Manual.zip