name: "Build nx-tweaks"

on:
  push:
    branches:
      - "main"
  workflow_dispatch:

jobs:
  Build-Uberhand:
    name: "Release"
    runs-on: "ubuntu-latest"
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Downloading latest Uberhand
        run: wget "https://github.com/efosamark/Uberhand-Overlay/releases/latest/download/ovlmenu.ovl" 

      - name: Compressing Manual Version
        run:  |
          mkdir -p "/switch/.overlays"
          mkdir -p "/switch/.packages/System Tweaks"
          mv ovlmenu.ovl /switch/.overlays/ovlmenu.ovl
          cp -r ./* "/switch/.packages/System Tweaks"
          zip -r "nx-tweaks-2Manual.zip" "switch"

      - name: Compressing Updater Version
        run:  |
          rm -rf switch
          mkdir -p "System Tweaks"
          cp -r ./* "System Tweaks"
          zip -r "nx-tweaks-1Updater.zip" "System Tweaks"

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          draft: true
          generate_release_notes: true
          files: |
            "nx-tweaks-1Updater.zip"
            "nx-tweaks-2Manual.zip"